### ISSUE TITLE
Error: Registry returned 404

### ISSUE THREAD

**Issue by kevinSuttle** [zalando/gitbook-structured-toc#1]
```bash
info: No version specified, resolve plugin gitbook-structured-toc

Error: Registry returned 404 for GET on https://registry.npmjs.org/gitbook-plugin-gitbook-structured-toc
```
Getting this on `gitbook install`. 

**book.json**
```javascript
"plugins": ["edit-link", "prism", "-highlight", "gitbook-structured-toc"],
```

**Comment by mostlymagic** [comment]
Hi Kevin, I'm pretty new at this, so sorry if I screwed up.

I use

"plugins": ["structured-toc"],

the convention seems to be that gitbook prepends "gitbook-plugin", and this artifact is published as "gitbook-plugin-structured-toc"

**Comment by kevinSuttle** [comment]
Ah ok. Thanks!

**Comment by kevinSuttle** [comment]
One problem down, another one opened: https://github.com/zalando/gitbook-structured-toc/issues/2
